kind: Deployment
apiVersion: apps/v1
metadata:
  name: traefik-deployment
  namespace: traefik
  labels:
    app: traefik
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traefik
  template:
    metadata:
      labels:
        app: traefik
    spec:
      serviceAccountName: traefik-account
      containers:
        - name: traefik
          image: traefik:v2.10
          args:
            - --api.insecure
            - --providers.kubernetesingress
            - --providers.kubernetescrd
            - --entrypoints.web.Address=:80
            - --entrypoints.prometheus.Address=:9090
            - --entrypoints.grafana.Address=:3000
          ports:
            - containerPort: 80
            - containerPort: 8080
            - containerPort: 9090
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-lb
  namespace: traefik
spec:
  type: LoadBalancer
  ports:
    - name: traefik-dashboard
      targetPort: 8080
      port: 8080
    - name: nginx
      targetPort: 80
      port: 80
    - name: prometheus
      targetPort: 9090
      port: 9090
    - name: grafana
      port: 3000
      targetPort: 3000
  selector:
    app: traefik
